/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLaunchRouteImport } from './routes/_authenticated/launch'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'
import { Route as AuthenticatedInvestigateIdRouteImport } from './routes/_authenticated/investigate.$id'
import { Route as ApiPublicDiscordStartRouteImport } from './routes/api/public/discord/start'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaunchRoute = AuthenticatedLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigateIdRoute =
  AuthenticatedInvestigateIdRouteImport.update({
    id: '/investigate/$id',
    path: '/investigate/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDiscordStartRoute = ApiPublicDiscordStartRouteImport.update({
  id: '/api/public/discord/start',
  path: '/api/public/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/launch': typeof AuthenticatedLaunchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$token': typeof RTokenRoute
  '/investigate/$id': typeof AuthenticatedInvestigateIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/start': typeof ApiPublicDiscordStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/launch': typeof AuthenticatedLaunchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$token': typeof RTokenRoute
  '/investigate/$id': typeof AuthenticatedInvestigateIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/start': typeof ApiPublicDiscordStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/launch': typeof AuthenticatedLaunchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/investigate/$id': typeof AuthenticatedInvestigateIdRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/start': typeof ApiPublicDiscordStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/keys'
    | '/launch'
    | '/settings'
    | '/sites'
    | '/api/chat'
    | '/r/$token'
    | '/investigate/$id'
    | '/report/$id'
    | '/api/public/discord/callback'
    | '/api/public/discord/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/keys'
    | '/launch'
    | '/settings'
    | '/sites'
    | '/api/chat'
    | '/r/$token'
    | '/investigate/$id'
    | '/report/$id'
    | '/api/public/discord/callback'
    | '/api/public/discord/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/keys'
    | '/_authenticated/launch'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/api/chat'
    | '/r/$token'
    | '/_authenticated/investigate/$id'
    | '/_authenticated/report/$id'
    | '/api/public/discord/callback'
    | '/api/public/discord/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordStartRoute: typeof ApiPublicDiscordStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/launch': {
      id: '/_authenticated/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof AuthenticatedLaunchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigate/$id': {
      id: '/_authenticated/investigate/$id'
      path: '/investigate/$id'
      fullPath: '/investigate/$id'
      preLoaderRoute: typeof AuthenticatedInvestigateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/discord/start': {
      id: '/api/public/discord/start'
      path: '/api/public/discord/start'
      fullPath: '/api/public/discord/start'
      preLoaderRoute: typeof ApiPublicDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedLaunchRoute: typeof AuthenticatedLaunchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedInvestigateIdRoute: typeof AuthenticatedInvestigateIdRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedLaunchRoute: AuthenticatedLaunchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedInvestigateIdRoute: AuthenticatedInvestigateIdRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordStartRoute: ApiPublicDiscordStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
